spring:
  datasource:
    url: jdbc:mysql://localhost:3309/ecommerce-spring-cloud?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: 'password12345'
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9003/realms/oauth2-demo-realm
          jwk-set-uri: http://localhost:9003/realms/oauth2-demo-realm/protocol/openid-connect/certs

pagination:
  page:
    size:
      default: 12

